apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-backup-pv
  labels:
    app: openshift-backup
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.17.0.2
    path: "/opt/nfs/etcd-backup-pv"
  capacity:
    storage: 10Gi
  claimRef:
    name: etcd-backup-pvc
    namespace: etcd-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-pvc
  labels:
    app: openshift-backup
spec:
  volumeName: etcd-backup-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
